* 1. PCA.
* 2. Reliability test.
* 3. Two-step cluster analysis.

TWOSTEP CLUSTER
  /CATEGORICAL VARIABLES=Q7
  /CONTINUOUS VARIABLES=Q1 Q2 Q3 Q4 Q5 Q6
  /DISTANCE LIKELIHOOD
  /NUMCLUSTERS FIXED=4
  /HANDLENOISE 0
  /MEMALLOCATE 64
  /CRITERIA INITHRESHOLD(0) MXBRANCH(8) MXLEVEL(3)
  /VIEWMODEL DISPLAY=YES
  /SAVE VARIABLE=Segment.
